[package]
name = "Profile"
version = "1.0.0"
authors = []

[addresses]
profile_system = "0x8d5583a22574889575196d064ed454e2a7e0d811ec8fc3fcbeabc30349347189"

[dev-addresses]


[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]


