[package]
name = "MoveDAO-official"
version = "0.0.3"
authors = []

[addresses]
movedao_addrx = "0x00eb30f24eab56506b8abaea431fb0c6f6aa64622018298b54b1c3d40006fc75"
aptos_framework = "0x1"

[dev-addresses]


[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]

